version: '3.7'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/app/dist
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config-redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pdi_test
    ports:
      - 5432:5432
    volumes:
      - ./config-postgres/postgres.conf:/etc/postgresql/9.6/main/postgresql.conf
      - ./config-postgres/pg_hba.conf:/etc/postgresql/9.6/main/pg_hba.conf
  elasticsearch: # Remove SSL check | Add volume
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: 'false'
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200/
    depends_on:
      - elasticsearch